import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,mkdtemp,rm,stat,unlink,writeFile} from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import {Readable} from 'node:stream';
import {generateKeyPairSync,sign} from 'node:crypto';
import {openStore} from '../storage.mjs';
import {createApp} from '../server.mjs';
import {purchaseLink,verifyGrant} from '../billing.mjs';
const scratch=new URL('../.test-work/',import.meta.url).pathname;
await mkdir(scratch,{recursive:true});
const metadata={name:'work.txt',kind:'final',mime:'text/plain'};
async function withStore(fn){const root=await mkdtemp(path.join(scratch,'storage-'));const store=await openStore(root);try{await fn(store,root);}finally{store.close();await rm(root,{recursive:true,force:true});}}
async function withApp(fn){const root=await mkdtemp(path.join(scratch,'api-'));const app=await createApp({root}),{server,store}=app;await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{await fn({base,store,server});}finally{await app.close();await rm(root,{recursive:true,force:true});}}
const post=body=>({method:'POST',headers:{'X-MBA-Client':'enzime'},body});
const put=store=>store.put(Readable.from([Buffer.from('abcdef')]),metadata);

test('duplicate objects retain one payload and select the latest import metadata',()=>withStore(async s=>{const a=await put(s);const b=await s.put(Readable.from(['abcdef']),{...metadata,name:'renamed.txt'});assert.equal(a.id,b.id);assert.equal(s.list().length,1);assert.equal(s.get(a.id).name,'renamed.txt');}));
test('reading state survives closing and reopening the database',async()=>{const root=await mkdtemp(path.join(scratch,'restart-'));let s=await openStore(root);try{const a=await put(s);s.saveState(a.id,{page:3,note:'mine'});s.close();s=await openStore(root);assert.deepEqual(s.readState(a.id),{page:3,note:'mine'});}finally{s.close();await rm(root,{recursive:true,force:true});}});
test('oversize imports do not publish catalog objects',()=>withStore(async s=>{await assert.rejects(s.put(Readable.from([Buffer.alloc(10)]),metadata,5),/size limit/);assert.equal(s.list().length,0);}));
test('deduplication detects a corrupted existing payload instead of hiding it',()=>withStore(async s=>{const a=await put(s);await writeFile(s.file(a.id),'broken');await assert.rejects(put(s),/integrity/);}));
test('profile, catalog, and SQLite sidecars are private to the OS user',{skip:process.platform==='win32'},()=>withStore(async(s,root)=>{await put(s);for(const entry of [root,path.join(root,'objects'),path.join(root,'tmp'),path.join(root,'catalog.sqlite'),path.join(root,'catalog.sqlite-wal'),path.join(root,'catalog.sqlite-shm')])assert.equal((await stat(entry)).mode&0o077,0,entry);}));
test('reading state rejects invalid values without replacing the saved note',()=>withStore(async s=>{const a=await put(s);s.saveState(a.id,{note:'preserve'});for(const value of [null,[],{page:0},{page:1.5},{time:-1},{font:999},{scroll:Infinity},{note:{}},{unknown:1}])assert.throws(()=>s.saveState(a.id,value));assert.deepEqual(s.readState(a.id),{note:'preserve'});}));
test('checkout fails closed and validates redemption configuration',()=>{assert.equal(purchaseLink({}),null);assert.throws(()=>purchaseLink({REVENUECAT_PURCHASE_URL:'https://evil.example/a'}));assert.throws(()=>purchaseLink({REVENUECAT_PURCHASE_URL:'https://pay.rev.cat/test'}));assert.equal(purchaseLink({REVENUECAT_PURCHASE_URL:'https://pay.rev.cat/test',REVENUECAT_REDEMPTION_ENABLED:'true'}),'https://pay.rev.cat/test');});
const {publicKey,privateKey}=generateKeyPairSync('ed25519');
function grant(sub='alice'){const bytes=Buffer.from(JSON.stringify({v:1,aud:'mba.robin.enzime',sub,exp:2000,capabilities:['studio']}));return {payload:bytes.toString('base64url'),signature:sign(null,bytes,privateKey).toString('base64url')};}
test('signed grants reject forgery, expiry, and wrong customer',()=>{const e=grant();assert.ok(verifyGrant(e,{publicKey,subject:'alice',now:1000}));assert.equal(verifyGrant(e,{publicKey,subject:'bob',now:1000}),null);assert.equal(verifyGrant(e,{publicKey,subject:'alice',now:2000000}),null);assert.equal(verifyGrant({...e,payload:Buffer.from('{}').toString('base64url')},{publicKey,subject:'alice',now:1000}),null);});
test('signed grants require nonempty expected and signed subjects',()=>{for(const subject of [undefined,null,'',' ',42]){const e=grant(subject);assert.equal(verifyGrant(e,{publicKey,subject,now:1000}),null);}const bytes=Buffer.from(JSON.stringify({v:1,aud:'mba.robin.enzime',exp:2000,capabilities:['studio']}));assert.equal(verifyGrant({payload:bytes.toString('base64url'),signature:sign(null,bytes,privateKey).toString('base64url')},{publicKey,now:1000}),null);});
test('local API rejects cross-origin access and missing application headers',()=>withApp(async({base})=>{assert.equal((await fetch(base+'/checkout')).status,503);assert.equal((await fetch(base+'/api/assets?kind=final&name=a',{method:'POST',body:'abc'})).status,403);assert.equal((await fetch(base+'/api/assets',{headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await fetch(base+'/api/assets',{headers:{'Sec-Fetch-Site':'cross-site'}})).status,403);assert.equal((await fetch(base+'/api/assets?kind=final&name=a',post('abcdef'))).status,201);}));
test('byte ranges support suffix, open-ended, and clipped endpoints',()=>withApp(async({base,store})=>{const a=await put(store);const url=base+'/api/assets/'+a.id+'/bytes';for(const [range,body,contentRange]of [['bytes=1-3','bcd','bytes 1-3/6'],['bytes=-3','def','bytes 3-5/6'],['bytes=-999','abcdef','bytes 0-5/6'],['bytes=2-','cdef','bytes 2-5/6'],['bytes=3-999','def','bytes 3-5/6']]){const r=await fetch(url,{headers:{Range:range}});assert.equal(r.status,206,range);assert.equal(r.headers.get('content-range'),contentRange);assert.equal(await r.text(),body);}for(const range of ['bytes=-0','bytes=-','bytes=30-40','bytes=3-1','bytes=0-1,3-4','bytes=9007199254740993-','bytes=-9007199254740993','bytes=0-9007199254740993']){const r=await fetch(url,{headers:{Range:range}});assert.equal(r.status,416,range);assert.equal(r.headers.get('content-range'),'bytes */6');}}));
test('empty objects serve normally and reject range reads',()=>withApp(async({base,store})=>{const a=await store.put(Readable.from([]),metadata);const url=base+'/api/assets/'+a.id+'/bytes';assert.equal(await(await fetch(url)).text(),'');assert.equal((await fetch(url,{headers:{Range:'bytes=-1'}})).status,416);}));
function rawRequest(base,path,parts=[],method='GET'){return new Promise((resolve,reject)=>{const req=http.request(base,{path,method,headers:{'X-MBA-Client':'enzime'}},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve({status:res.statusCode,body:Buffer.concat(chunks).toString('utf8')}));});req.on('error',reject);let index=0;const writeNext=()=>{if(index===parts.length)return req.end();req.write(parts[index++]);setImmediate(writeNext);};writeNext();});}
test('split UTF-8 request chunks round-trip notes without corruption',()=>withApp(async({base,store})=>{const a=await put(store);const body=Buffer.from(JSON.stringify({note:'café 日本語 🐣'}));const result=await rawRequest(base,'/api/state/'+a.id,[...body].map(n=>Buffer.from([n])),'POST');assert.equal(result.status,200);assert.equal(store.readState(a.id).note,'café 日本語 🐣');}));
test('state limit counts UTF-8 bytes and keeps earlier state on rejection',()=>withApp(async({base,store})=>{const a=await put(store);store.saveState(a.id,{note:'old'});assert.equal((await fetch(base+'/api/state/'+a.id,post(JSON.stringify({note:'🐣'.repeat(20000)})))).status,413);assert.equal(store.readState(a.id).note,'old');}));
test('malformed request targets fail only their own request',()=>withApp(async({base})=>{assert.equal((await rawRequest(base,'http://[')).status,400);assert.equal((await fetch(base+'/api/config')).status,200);}));
test('missing object bytes fail without terminating the broker',()=>withApp(async({base,store})=>{const a=await put(store);await unlink(store.file(a.id));assert.equal((await fetch(base+'/api/assets/'+a.id+'/bytes')).status,404);assert.equal((await fetch(base+'/api/assets')).status,200);}));
test('concurrent independent state patches preserve notes and media time',()=>withApp(async({base,store})=>{const a=await put(store);store.saveState(a.id,{page:2,time:10});const url=base+'/api/state/'+a.id;const replies=await Promise.all([fetch(url,post(JSON.stringify({note:'fuel list'}))),fetch(url,post(JSON.stringify({time:42})))]);assert.ok(replies.every(r=>r.status===200));assert.deepEqual(store.readState(a.id),{page:2,time:42,note:'fuel list'});assert.equal((await fetch(url,post(JSON.stringify({time:-1})))).status,400);assert.deepEqual(store.readState(a.id),{page:2,time:42,note:'fuel list'});}));

test('PR3 article keys survive strict state validation and independent patches',()=>withApp(async({base,store})=>{const a=await put(store),url=base+'/api/state/'+a.id;store.saveState(a.id,{key:'C/Water',page:1,font:18});assert.equal((await fetch(url,post(JSON.stringify({time:12})))).status,200);assert.deepEqual(store.readState(a.id),{key:'C/Water',page:1,font:18,time:12});for(const key of [null,42,{},'C/Water\u0000'])assert.equal((await fetch(url,post(JSON.stringify({key})))).status,400);assert.equal(store.readState(a.id).key,'C/Water');}));
test('malformed UTF-8 is rejected without replacing saved reading state',()=>withApp(async({base,store})=>{const a=await put(store);store.saveState(a.id,{note:'old'});const result=await rawRequest(base,'/api/state/'+a.id,[Buffer.from('{"note":"'),Buffer.from([0xc3,0x28]),Buffer.from('"}')],'POST');assert.equal(result.status,400);assert.equal(store.readState(a.id).note,'old');}));
