import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const source=await readFile(new URL('../public/app.mjs',import.meta.url),'utf8');
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
async function reader(fetcher){const elements=new Map();const element=tag=>({tag,children:[],style:{},value:'',scrollTop:0,textContent:'',replaceChildren(...c){this.children=c;},append(c){this.children.push(c);},querySelector(selector){return this.children.find(c=>selector.split(',').includes(c.tag))||null;}});const document={getElementById(id){if(!elements.has(id))elements.set(id,element(id));return elements.get(id);},createElement:element};const context=vm.createContext({document,fetch:async(url,opts)=>{if(url==='/api/config')return {ok:true,json:async()=>({checkoutReady:false})};if(url==='/api/assets')return {ok:true,json:async()=>[]};return fetcher(url,opts);}});await vm.runInContext('(async()=>{'+source+';globalThis.reader={save,openAsset,set(values){current=values.current;page=values.page??1;font=values.font??19;}};})()',context);return {api:context.reader,get:document.getElementById.bind(document),element};}
const json=value=>({ok:true,json:async()=>value});
test('a save uses its initiating asset and reader snapshot despite navigation',async()=>{const pending=deferred();const writes=[];const r=await reader(async(url,opts)=>{if(!opts)return pending.promise;writes.push([url,JSON.parse(opts.body)]);return json({});});r.api.set({current:{id:'old'},page:7,font:23});r.get('reading').scrollTop=150;r.get('reading').append({...r.element('audio'),currentTime:31});const saving=r.api.save({note:'original'});r.api.set({current:{id:'new'},page:1,font:19});r.get('reading').scrollTop=0;pending.resolve(json({note:'prior'}));await saving;assert.deepEqual(writes,[['/api/state/old',{note:'original',page:7,scroll:150,font:23,time:31}]]);});
test('late text loading cannot append the prior work into the current reader',async()=>{const pending=deferred();const r=await reader(async url=>url.endsWith('/bytes')?pending.promise:json({}));const loading=r.api.openAsset({id:'old',name:'Old',kind:'final',size:5});await new Promise(setImmediate);await r.api.openAsset({id:'new',name:'New',kind:'model',size:5});pending.resolve({ok:true,text:async()=>'old text'});await loading;assert.equal(r.get('work-title').textContent,'New');assert.equal(r.get('reading').children.length,1);assert.match(r.get('reading').children[0].textContent,/Local inference/);assert.equal(r.get('status').textContent,'Opened New');});
test('pausing media snapshots its time before the state fetch',async()=>{const pending=deferred();let reads=0;const writes=[];const r=await reader(async(url,opts)=>{if(opts){writes.push(JSON.parse(opts.body));return json({});}return ++reads===1?json({}):pending.promise;});await r.api.openAsset({id:'audio',name:'Audio',kind:'audio'});const media=r.get('reading').children[0];media.currentTime=42;const saving=media.onpause();media.currentTime=0;pending.resolve(json({note:'keep'}));await saving;assert.deepEqual(writes,[{note:'keep',time:42}]);});
