// Tauri build script.
//
// The app's command permissions (`allow-<command>` / `deny-<command>`) are
// autogenerated from this explicit command list — the build script cannot see
// the `tauri::generate_handler!` set in src/lib.rs, so the commands must be
// declared here for the capability files in `capabilities/` to resolve.
// Keep this list in sync with the `invoke_handler` registration in src/lib.rs.

const COMMANDS: &[&str] = &[
    "enzime_version",
    "zim_open",
    "zim_get_article",
    "zim_list_articles",
    "zim_metadata",
    "zim_close",
    "zim_search",
    "ai_chat",
    "ai_chat_stream",
    "ai_voice_chat",
    "ai_load_model",
    "ai_unload_model",
    "annotations_list",
    "annotations_create",
    "annotations_delete",
    "annotations_export",
    "annotations_import",
    "bookmarks_list",
    "bookmarks_toggle",
    "chat_history_list",
    "chat_history_append",
    "chat_history_clear",
    "settings_get",
    "settings_set",
    "entitlement_check",
    "billing_open_paywall",
    "billing_restore_purchases",
    "device_probe",
    "variant_current",
    "variant_override",
    "model_fetch",
    "model_present",
    "model_import_from_media",
    "sidecar_create",
    "sidecar_export",
    "sidecar_export_json",
    "sidecar_import",
    "sidecar_list",
    "sidecar_delete",
    "trust_get",
    "trust_set",
    "trust_list",
    "chunk_ingest",
    "pack_catalog_list",
    "pack_install",
    "pack_uninstall",
    "pack_search_global",
    "app_update_check",
    "app_update_apply",
    "window_state_save",
    "window_state_restore",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri build");
}
